# Generated by Django 5.1.3 on 2025-01-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='itinerary',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='city',
            field=models.CharField(max_length=255),
        ),
    ]
