# Generated by Django 5.1.3 on 2025-04-06 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0003_alter_itinerary_options_itinerary_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_itineraries', to=settings.AUTH_USER_MODEL),
        ),
    ]
