# Generated by Django 5.1.3 on 2025-04-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0004_itinerary_bookmarked_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={},
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='bookmarked_by',
        ),
    ]
